[__config__]
verify_cert = false
sort_version_key = "awesomeversion"
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

[sipeed_licheepi4a-debian-null] # RevyOS is seen as Debian
source = "regex"
url = "https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/"
regex = '<a href="(\d{8})/" title="\1">\1/</a>'
